function Enemy(x,y){
	this.x=x;
	this.y=y;
	this.r=30;
	this.dirX=1;
	this.toDelete=false;

	this.show=function(){
		fill(255,150,100);
		if(this.r<7){
			this.toDelete=true;
		}else{
			ellipse(this.x,this.y,this.r*2,this.r*2);
		}
	}
	this.move=function(){
		this.x+=this.dirX;
	}
	this.shiftDown=function(){
		this.dirX*=-1;
		this.y+=this.r;
	}
	this.shiftUp=function(){
		this.dirX*=-1;
		this.y-=this.r;
	}
	this.weaken=function(){
		this.r-=2;
	}
}